version: '3'
services:
  monitoring:
    container_name: system-sensors
    build: .
    restart: always
    devices:
      - /dev/vchiq
    volumes:
      - ./config:/app/config
    environment:
      - MQTT_HOST=localhost
      - MQTT_PORT=1883
      - DEVICE_NAME=myPi
      - LD_LIBRARY_PATH=/opt/vc/lib
