version: '3.2'

services:
  monitoring:
    container_name: system-sensors
    build: .
    restart: always
    devices:
      - /dev/vchiq
    volumes:
      - ./config:/app/config
      - /etc/os-release:/app/host/os-release:ro
      - /opt/vc:/opt/vc:ro
      - /proc/device-tree/model:/app/host/proc/device-tree/model:ro
    environment:
      - MQTT_HOST=localhost
      - MQTT_PORT=1883
      - DEVICE_NAME=myPi
      - LD_LIBRARY_PATH=/opt/vc/lib
